### ISSUE TITLE
TypeError: data.fail is not a function

### ISSUE THREAD

**Issue by pierresh** [push-sdk/push-oppo#4]
Hello,

When I start a Node project with this plugin, I get the following error:

```bash
(node:12201) UnhandledPromiseRejectionWarning: TypeError: data.fail is not a function
    at Oppo.push (--/node_modules/push-oppo/lib/**push-oppo.js:57:12**)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:12201) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12201) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by pierresh** [comment]
Actually, my **masterSecret** was wrong, now it is ok. Maybe if there is an error when getting a token, it should be reported in a nicer way :)
